#
# This file contains configuration flags to customize your site
#
# Name of your site (displayed in the header)
title: Tay's Blog
# Short bio or description (displayed in the header)
description: My Journey to A&M

# My name is Taylor Hartman. I am a senior at Texas A&M University. I am a Communication major and pursing a minor in English. Texas A&M has been my dream school since I was young. I am writing this blog to help inspire others. I remember thinking I was not smart or good enough for A&M and gave up on my dream. At least that is what I thought. Starting my college career off at two community colleges is what led me here. Although I would have never thought that was the case if you were to ask me four or three years ago. Moral of the story is if I would have settled and not tried to push myself then or course I would have never got into A&M. Yet, since I would not let my self settle for the easy option, I was able to chase my dreams.
# !! DON'T EDIT BELOW THIS MESSAGE
#
# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
